steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ["-c", "docker login --username=$$USERNAME --password=$$PASSWORD"]
  secretEnv: ["USERNAME", "PASSWORD"]
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build' 
  - '-t' 
  - 'vonwig/altdservice:$TAG_NAME' 
  - '--build-arg' 
  - 'COMMIT_SHA=$COMMIT_SHA' 
  - '-f' 
  - 'Dockerfile' 
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "vonwig/altdservice:$TAG_NAME"]
availableSecrets:
   secretManager:
   - versionName: projects/personalsdm-216019/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/personalsdm-216019/secrets/docker-username/versions/1
     env: 'USERNAME'
