steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["login", "--username=$$USERNAME", "--password=$$PASSWORD"]
  secretEnv: ["USERNAME", "PASSWORD"]
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build' 
  - '-t' 
  - 'slimslenderslacks/altdservice:$TAG_NAME' 
  - '--build-arg' 
  - 'COMMIT_SHA=$COMMIT_SHA' 
  - '-f' 
  - 'Dockerfile' 
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "slimlsenderslacks/altdservice:$TAG_NAME"]
  secretEnv: ["USERNAME", "PASSWORD"]
availableSecrets:
   secretManager:
   - versionName: projects/personalsdm-216019/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/personalsdm-216019/secrets/docker-username/versions/1
     env: 'USERNAME'
